name: Run Pester Tests

on: [push]

jobs:
  test:
    name: Run Pester Tests
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Pester Tests
        run: .\tasks.ps1 test:e2e
        shell: pwsh
