name: Run Pester Tests

on: [push]

jobs:
  test:
    name: Run Pester Tests
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Pester Tests
        run: Invoke-Pester -Path .\tests -Output Detailed
        shell: pwsh
