name: Version Bump on Push to Main

on:
  push:
    branches:
      - main

jobs:
  version-bump:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        